---
- name: Manage K8s Playbook
  hosts: control_plane_lab_4
  become: yes
  tasks:
  - name: Get Cluster Namespaces Info
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Namespace
      kubeconfig: /etc/kubernetes/admin.conf
    register: namespaces

  - name: Print all namespace names
    debug:
      msg: "{{ namespaces.resources | map(attribute='metadata.name') | list }}"

  - name: Get Cluster Running Pods
    kubernetes.core.k8s_info:
      kind: Pod
      kubeconfig: /etc/kubernetes/admin.conf
      field_selectors:
        - status.phase=Running
    register: pods

  - name: Print all pods
    debug:
      msg: "{{ pods.resources | map(attribute='metadata.name') | list }}"

  - name: Create K8s Namespace
    kubernetes.core.k8s:
      name: web-demo
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: /etc/kubernetes/admin.conf


  - name: Deploy Nginx via Deployment
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          namespace: web-demo
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: nginx
                  ports:
                    - containerPort: 80
      kubeconfig: /etc/kubernetes/admin.conf

